### ISSUE TITLE
Periodic error popup and application crash

### ISSUE THREAD

**Issue by wesoos** [opentok/opentok-windows-sdk-samples#56] opened 2023-06-13 14:00 UTC
Hello, we are intermittently receiving windows error popups in our application.  The popup mentions memory, but unfortunately I haven't been able to grab a screen shot of it, and we don't have anything in our own logs.  Below is what we get in event viewer.

Faulting application name: TEKControlAllBox.exe, version: 4.0.7.0, time stamp: 0x641de100
Faulting module name: opentok.DLL, version: 2.25.1.0, time stamp: 0x645d8619
Exception code: 0xc0000005
Fault offset: 0x000000000006062d
Faulting process id: 0x2ac4
Faulting application start time: 0x01d99a560cdcf6fe
Faulting application path: C:\TEKWave Solutions\TEKControl AllBox\TEKControlAllBox.exe
Faulting module path: C:\TEKWave Solutions\TEKControl AllBox\opentok.DLL
Report Id: 21f14154-f218-4cfb-8f41-24345f1631e5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by wesoos** [comment] 2023-06-13 14:28
![Screenshot_3](https://github.com/opentok/opentok-windows-sdk-samples/assets/7227622/233abee2-a547-4a1b-9173-dcb65603aa2a)

Attached is a screenshot of the popup

**Comment by wesoos** [comment] 2023-06-14 14:56
Hello, any ideas here?

**Comment by v-kpheng** [comment] 2023-06-14 22:42
@wesoos, thanks for letting us know about this issue.

Windows SDK 2.25.2 was released recently.  Are you able to reproduce on that version as well?  Also, are you able to reproduce the issue on our sample apps?  If you can reproduce with the sample apps, that will help tremendously.

**Comment by wesoos** [comment] 2023-06-14 23:01
Hello, yes I'm using the latest version and having the same issue.

I will have to try and see if I can reproduce with samples.  But I'm fairly certain the issue is when disposing the Session object.  There is either a memory leak or memory is being accessed incorrectly...

**Comment by wesoos** [comment] 2023-06-14 23:52
Hello,

Attached is your sample apps.  I have modified the BasicVideoChat app slightly with somewhat of what I'm doing, especially when closing the window.  I haven't technically reproduced it while running outside of debugger, but did get an access violation while debugging once and the app crashed.  I test by opening the video window and closing constantly.

Thanks
[opentok-windows-sdk-samples-main.zip](https://github.com/opentok/opentok-windows-sdk-samples/files/11751397/opentok-windows-sdk-samples-main.zip)

**Comment by wesoos** [comment] 2023-06-15 12:59
Are there any debug logging I can turn on?

**Comment by v-kpheng** [comment] 2023-06-15 17:19
Thanks, @wesoos, for the sample app.  We tried to reproduce the crash but aren't able to.  I think we might be missing some nuance, though.  Any ideas?

**Comment by wesoos** [comment] 2023-06-15 21:02
I'm not sure what else to do.  My application is much bigger than the sample app, but the crash is happening in the Session.Dispose().  Is there any logging we can turn on, or can you can you guys add any logging that would help diagnose what's happening, and I'll help troubleshoot...

**Comment by wesoos** [comment] 2023-06-16 18:47
Hello, any updates?

**Comment by wesoos** [comment] 2023-06-20 21:39
Hello, any updates?

**Comment by wesoos** [comment] 2023-06-22 17:11
Hello, any update?

**Comment by wesoos** [comment] 2023-06-26 21:50
Any update on this?

**Comment by wesoos** [comment] 2023-07-07 16:48
Hello, I need to know if this is being addressed and what the status is?  I am a paying customer and this library is crashing my application.  I am willing to help where I can, but there are no logs to look at.

Please respond as soon as possible..

Thanks

**Comment by v-kpheng** [comment] 2023-07-11 16:27
> Hello, I need to know if this is being addressed and what the status is? I am a paying customer and this library is crashing my application. I am willing to help where I can, but there are no logs to look at.
> 
> Please respond as soon as possible..
> 
> Thanks

@wesoos, sorry, I was on vacation.  Let me ask engineering.

**Comment by wesoos** [comment] 2023-07-12 15:56
@v-kpheng Thanks.  Any update?

**Comment by v-kpheng** [comment] 2023-07-14 14:47
> @v-kpheng Thanks. Any update?

@wesoos, I spoke with engineering.  There's some improvements in the upcoming 2.26.0 that may help.  ETA for that is in late August.

**Comment by wesoos** [comment] 2023-08-07 19:46
Hello, can I get an update on the ETA?

**Comment by v-kpheng** [comment] 2023-08-07 20:02
@wesoos, it's fluid.  We're still aiming for mid-August, but it may slip to late August.

**Comment by wesoos** [comment] 2023-08-21 18:53
I see there is a pre-release for 2.26.0-release

Can you please let me know what was fixed in it for this issue?

**Comment by v-kpheng** [comment] 2023-08-22 18:08
@wesoos, Windows SDK 2.26.0 was released last week.  Please let me know if the issue persists.  Thanks!

**Comment by wesoos** [comment] 2023-08-22 19:13
@v-kpheng Thank you.  Can you please let me know what particularly was fixed as it relates to this issue?

**Comment by wesoos** [comment] 2023-08-22 21:25
Hello, this issue still persists.  I have enable debug logging.  Please see attached and advise...
[Log-Debug20230822.zip](https://github.com/opentok/opentok-windows-sdk-samples/files/12413142/Log-Debug20230822.zip)

**Comment by v-kpheng** [comment] 2023-08-24 12:42
@wesoos, since you filed this same issue with our Support team, let's move the conversation there, please.  I'll close this ticket.

**Closed by v-kpheng** 2023-08-24 12:42 UTC
